import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { useSelector } from "react-redux";
import Authentication from "../container/authentication";
import Messenger from "../container/messenger";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const state = useSelector((state:any)=>state?.auth)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!!state.token ? <Messenger/> :<Authentication/>}
    </div>
  );
};

export default Home;
